### ISSUE TITLE
QA: Can it be used with React Native?

### ISSUE THREAD

**Issue by yarapolana** [idanlo/react-spotify-api#218]
This looks very promising I was wondering if it can be used with react-native and possibly expo.
I saw the html elements but they can be easily switched to the react native elements, is there anything that would stop this from working in react native and expo?
Thanks!

**Comment by idanlo** [comment]
Hey, thanks for your interest in this library!
I think it should work in React Native, since there are no HTML elements used in this library, I think the HTML elements you are referring to are in the `src/App.jsx` file - these file is for the demo of the library, and is not included in the build, meaning if you install this package using `npm` or `yarn` you should not have this file, and therefore there shouldn't be any HTML elements, and it should work in React Native.
Let me know if you need further guidance
